version: "3.3"
   
services:
  web:
    build: .
    command: /bin/sh -c /code/entrypoint.sh
    volumes:
      - database_volume:/code/db/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev

volumes:
  database_volume: {}
