version: "3.9"
   
services:
  web:
    build: .
    command: pipenv run gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - database_volume:/market_sim/db.sqlite3
      - static_volume:/code/static
    expose:
      - 8000

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/code/static
      - type: bind
        source: ./nginx_config/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  database_volume:
  static_volume: