version: "3.3"

services:
  web:
    build: .
    command: /bin/sh -c /code/entrypoint.dev.sh
    volumes:
      - database_volume:/db/
      - .:/code
      - ./backups:/backups
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev

volumes:
  database_volume: {}
