version: "3.3"
   
services:
  web:
    build: .
    command: /bin/sh -c /code/entrypoint.prod.sh
    volumes:
      - database_volume:/market_sim/db.sqlite3
      - static_volume:/code/static
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/code/static
      - type: bind
        source: ./nginx_config/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  database_volume:
  static_volume: