version: "3.3"
   
services:
  web:
    restart: always
    build: .
    command: /bin/sh -c /code/entrypoint.prod.sh
    volumes:
      - database_volume:/market_sim/db.sqlite3
      - static_volume:/code/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    networks:
      - nginx_nginx-proxynet

  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - static_volume:/code/static
      - type: bind
        source: ./nginx_config/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 1337:80
    depends_on:
      - web
    environment:
      - VIRTUAL_HOST=market.dataekspeditioner.dk
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=market.dataekspeditioner.dk
      - LETSENCRYPT_EMAIL=dybber@di.ku.dk
      - url=https://market.dataekspeditioner.dk
    networks:
      - nginx_nginx-proxynet


volumes:
  database_volume:
  static_volume:

networks:
  nginx_nginx-proxynet:
    external: true